version: '3.8'

services:
  web:
    image: amoghsharanar/serve-smart:latest
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fos_db
      MYSQL_USER: fos_user
      MYSQL_PASSWORD: fos_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/fos_db.sql:/docker-entrypoint-initdb.d/fos_db.sql

volumes:
  db_data:
