version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/fos_db.sql:/docker-entrypoint-initdb.d/fos_db.sql

volumes:
  db_data:
