name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/serve-smart:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove existing containers
            docker-compose -f ~/serve-smart/docker-compose.yml down -v || true

            # Remove old application directory
            rm -rf ~/serve-smart

            # Clone the latest code
            git clone https://github.com/amogh-sharanar28/Serve-Smart.git ~/serve-smart

            # Navigate to the project directory
            cd ~/serve-smart

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/serve-smart:latest

            # Start the application using Docker Compose
            docker-compose up -d
