name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: amoghsharanar/serve-smart:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Ensure docker group exists
            if ! getent group docker > /dev/null; then
              sudo groupadd docker
            fi

            # Add user to docker group
            sudo usermod -aG docker $USER

            # Run docker commands using sudo (to avoid needing newgrp)
            sudo docker stop serve-smart || true
            sudo docker rm serve-smart || true
            sudo docker rmi amoghsharanar/serve-smart:latest || true
            sudo docker pull amoghsharanar/serve-smart:latest
            sudo docker run -d -p 80:3000 --name serve-smart amoghsharanar/serve-smart:latest
